[build]
target = "armv7a-none-eabi"

[target.armv7a-none-eabi]
runner = "arm-none-eabi-gdb -q -x debug.gdb"
rustflags = [
    "-C", "link-arg=--script=linker.ld",
]

[alias]
flash = "objcopy -- -O binary boot/kernel7.img"
